 unsigned char   txt[260][30] =  {"",
"down   1   fache",
"down   2   fache",
"down   3   fache",
"down   4   fache",
"down   5   fache",
"down   6   fache",
"down   7   fache",
"down   8   fache",
"down   9   fache",
"down   10   fache",
"down   11   fache",
"down   12   fache",
"down   13   fache",
"down   14   fache",
"down   15   fache",
"down   16   fache",
"down   17   fache",
"down   18   fache",
"down   19   fache",
"down   21   fache",
"down   1   jieche",
"down   2   jieche",
"down   3   jieche",
"down   4   jieche",
"down   5   jieche",
"down   6   jieche",
"down   7   jieche",
"down   8   jieche",
"down   9   jieche",
"down   10   jieche",
"down   11   jieche",
"down   12   jieche",
"down   13   jieche",
"down   14   jieche",
"down   15   jieche",
"down   16   jieche",
"down   17   jieche",
"down   18   jieche",
"down   19   jieche",
"down   21   jieche",
"down   1   tongguo",
"down   2   tongguo",
"down   3   tongguo",
"down   4   tongguo",
"down   5   tongguo",
"down   6   tongguo",
"down   7   tongguo",
"down   8   tongguo",
"down   9   tongguo",
"down   10   tongguo",
"down   11   tongguo",
"down   12   tongguo",
"down   13   tongguo",
"down   14   tongguo",
"down   15   tongguo",
"down   16   tongguo",
"down   17   tongguo",
"down   18   tongguo",
"down   19   tongguo",
"down   21   tongguo",
"jin    1   tingche",
"jin    2   tingche",
"jin    3   tingche",
"jin    4   tingche",
"jin    5   tingche",
"jin    6   tingche",
"jin    7   tingche",
"jin    8   tingche",
"jin    9   tingche",
"jin    10   tingche",
"jin    11   tingche",
"jin    12   tingche",
"jin    13   tingche",
"jin    14   tingche",
"jin    15   tingche",
"jin    16   tingche",
"jin    17   tingche",
"jin    18   tingche",
"jin    19   tingche",
"jin    21   tingche",
"jing   1   tongguo",
"jing   2   tongguo",
"jing   3   tongguo",
"jing   4   tongguo",
"jing   5   tongguo",
"jing   6   tongguo",
"jing   7   tongguo",
"jing   8   tongguo",
"jing   9   tongguo",
"jing   10   tongguo",
"jing   11   tongguo",
"jing   12   tongguo",
"jing   13   tongguo",
"jing   14   tongguo",
"jing   15   tongguo",
"jing   16   tongguo",
"jing   17   tongguo",
"jing   18   tongguo",
"jing   19   tongguo",
"jing   21   tongguo",
"up     1   fache",
"up     2   fache",
"up     3   fache",
"up     4   fache",
"up     5   fache",
"up     6   fache",
"up     7   fache",
"up     8   fache",
"up     9   fache",
"up     10   fache",
"up     11   fache",
"up     12   fache",
"up     13   fache",
"up     14   fache",
"up     15   fache",
"up     16   fache",
"up     17   fache",
"up     18   fache",
"up     19   fache",
"up     21   fache",
"up     1   jieche",
"up     2   jieche",
"up     3   jieche",
"up     4   jieche",
"up     5   jieche",
"up     6   jieche",
"up     7   jieche",
"up     8   jieche",
"up     9   jieche",
"up     10   jieche",
"up     11   jieche",
"up     12   jieche",
"up     13   jieche",
"up     14   jieche",
"up     15   jieche",
"up     16   jieche",
"up     17   jieche",
"up     18   jieche",
"up     19   jieche",
"up     21   jieche",
"up     1   tongguo",
"up     2   tongguo",
"up     3   tongguo",
"up     4   tongguo",
"up     5   tongguo",
"up     6   tongguo",
"up     7   tongguo",
"up     8   tongguo",
"up     9   tongguo",
"up     10   tongguo",
"up     11   tongguo",
"up     12   tongguo",
"up     13   tongguo",
"up     14   tongguo",
"up     15   tongguo",
"up     16   tongguo",
"up     17   tongguo",
"up     18   tongguo",
"up     19   tongguo",
"up     21   tongguo",
"jin    1   tingche",
"jin    2   tingche",
"jin    3   tingche",
"jin    4   tingche",
"jin    5   tingche",
"jin    6   tingche",
"jin    7   tingche",
"jin    8   tingche",
"jin    9   tingche",
"jin    10   tingche",
"jin    11   tingche",
"jin    12   tingche",
"jin    13   tingche",
"jin    14   tingche",
"jin    15   tingche",
"jin    16   tingche",
"jin    17   tingche",
"jin    18   tingche",
"jin    19   tingche",
"jin    21   tingche",
"jing   1   tongguo",
"jing   2   tongguo",
"jing   3   tongguo",
"jing   4   tongguo",
"jing   5   tongguo",
"jing   6   tongguo",
"jing   7   tongguo",
"jing   8   tongguo",
"jing   9   tongguo",
"jing   10   tongguo",
"jing   11   tongguo",
"jing   12   tongguo",
"jing   13   tongguo",
"jing   14   tongguo",
"jing   15   tongguo",
"jing   16   tongguo",
"jing   17   tongguo",
"jing   18   tongguo",
"jing   19   tongguo",
"jing   21   tongguo",
"down   1   jiejin    ",
"down   2   jiejin    ",
"down   3   jiejin    ",
"down   jin    zhan",
"down   1   liqu",
"down   2   liqu",
"down   3   liqu",
"down   chuzhan",
"空",
"空",
"up     1   jiejin    ",
"up     2   jiejin    ",
"up     3   jiejin    ",
"up     jin    zhan",
"up     1   liqu",
"up     2   liqu",
"up     3   liqu",
"up     chuzhan",
"空",
"空",
"信息中断",
"通过二三八二信号点",
"通过二四八八信号点",
"通过二四七三信号点",
"通过二三六五信号点",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"空",
"枣阳站",
"枣阳站",
}; 
 
